New detector: `EtaLikeSimplifications`
nowarp/misti pull request #198
Opened 2024-10-24 12:50 UTC by Esorat

Closes #92 

- [x] I have updated `CHANGELOG.md`
- [x] I have added tests to demonstrate the contribution is correctly implemented
- [x] No test failures were reported when running `yarn test-all`
- [x] I did not do unrelated and/or undiscussed refactorings

2024-10-28 13:28 UTC, jubnzv commented on src/detectors/builtin/etaLikeSimplifications.ts
> +    if (expr.kind === "boolean") {
Let's use the constant evaluator

2024-11-01 14:02 UTC, jubnzv requested changes
The core logic seems correct. Let's adjust the implementation.

2024-11-01 14:02 UTC, jubnzv commented on src/detectors/builtin/etaLikeSimplifications.ts
> +      if (binaryExpr.op === "==") {
I would simplify creating a constant here: `const negated = binaryExpr.op === "=="` and using it in this function.

2024-11-01 14:02 UTC, jubnzv commented on src/detectors/builtin/etaLikeSimplifications.ts
> +    return "condition";
What does it mean?

2024-11-01 14:02 UTC, jubnzv commented on src/detectors/builtin/etaLikeSimplifications.ts
> +                suggestion: "Replace with 'return condition;'",
Pretty print it?

2024-11-01 14:03 UTC, jubnzv commented
We should also merge the master in this branch and resolve conflicts, including those in the changelog.

2024-11-04 02:37 UTC, jubnzv commented on src/detectors/builtin/etaLikeSimplifications.ts
> +    expr: AstExpression | null | undefined,
I'm not sure why it is resolved without any changes.

2024-11-04 05:32 UTC, Esorat commented on src/detectors/builtin/etaLikeSimplifications.ts
> +    expr: AstExpression | null | undefined,
I included both null and undefined in parameter type. This allows function to handle both cases without requiring type assertions or conversions at the call site.

2024-11-04 09:51 UTC, jubnzv approved these changes
LGTM

2024-11-04 09:51 UTC, jubnzv commented on CHANGELOG.md
> +- `EtaLikeSimplifications` detector: PR [#198](https://github.com/nowarp/misti/pull/198)
```suggestion
```

2024-11-04 09:52 UTC, merged